# Generated by Django 4.0.4 on 2022-04-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='author',
            field=models.CharField(default='anonymous', max_length=30),
        ),
        migrations.AddField(
            model_name='posts',
            name='describe',
            field=models.TextField(default='DataFlair Django tutorials'),
        ),
        migrations.AddField(
            model_name='posts',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='posts',
            name='picture',
            field=models.ImageField(default='default value', upload_to=''),
        ),
    ]
